version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - dbvectorizer-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/chromadb:/app/data/chromadb
    env_file:
      - .env
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dbvectorizer-network

networks:
  dbvectorizer-network:
    driver: bridge 